branch-defaults:
  default:
    environment: Finalapp-env
deploy:
  artifact: www/Archive.zip
environment-defaults:
  Finalapp-env:
    branch: null
    repository: null
global:
  application_name: final-app
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
